### ISSUE TITLE
Newlines in comments

### ISSUE THREAD

**Issue by angelinahli** [Sage-Future/fatebook#13]
Fatebook seems to strip newlines in comments. If easy to fix, I'd find newline support helpful! This would be especially helpful for cases where I'm trying to create lists, or want to write multiple paragraphs to share some context.

![image](https://github.com/Sage-Future/fatebook/assets/25024154/d4246424-4c11-4bc3-8f74-cb96966105e6)

![image](https://github.com/Sage-Future/fatebook/assets/25024154/1008b96b-af22-48a1-b7ce-8f14aaac1ab9)

**Comment by adam-binks** [comment]
Thanks for reporting Angelina - fixed!
<img width="624" alt="image" src="https://github.com/Sage-Future/fatebook/assets/13518594/1ad05084-d9ef-4b27-b7f7-bdca64a77804">
