### ISSUE TITLE
Feature request: filter by tag

### ISSUE THREAD

**Issue by Sha-yol** [Sage-Future/fatebook#15]
Hi,
I would like to request the following feature: an option to filter the "Your Forecasts" list by tag, similarly to filtering the calibration graph and Brier score on the right side of the page.

**Comment by adam-binks** [comment]
Thanks @Sha-yol! You can see all the questions in a tag by clicking on the tag itself (either in the track record sidebar or below a question that you've tagged). Does that help?

**Comment by Sha-yol** [comment]
Whoops, I think I even knew that and forgot, but for some reason I expected
the button with the filter above the "Your predictions" list to open a list
of tags, or the search box to allow typing tags. Not sure if something
should be changed then - you can close this issue.
