### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by makew0rld** [Sage-Future/fatebook#22]
What is the license for this code? It's nice it's on GitHub, but without a license file it is proprietary by default and I can't do anything with it. It would be great if a license file was added to clarify this.

If you are unfamiliar with software licensing, GitHub has a very helpful microsite: https://choosealicense.com/

**Comment by makew0rld** [comment]
Any update on this? Thanks. @adam-binks @jonnyspicer

**Comment by jonnyspicer** [comment]
Hey, thanks for the chase - I'm not currently working on the project full time, and Adam is on holiday, but I know that it's on his to-do list.

**Comment by makew0rld** [comment]
Good to hear, thanks!

**Comment by adam-binks** [comment]
Thanks for raising this - I've added MIT license 730c647

By the way, I'd be interested to hear more about what you plan to use this for. Want to get in touch at adam@sage-future.org?

**Comment by makew0rld** [comment]
Thanks! I don't have any special use at the moment. Originally I wanted to make my own software like this, then I discovered Fatebook.

In the short term I plan on testing Fatebook for personal usage and seeing how it goes. Thanks a lot of working on it, it's a great concept!

-------- Message d'origine --------
