### ISSUE TITLE
Is there a way of changing which Slack channel a team's questions are synced with?

### ISSUE THREAD

**Issue by patbl** [Sage-Future/fatebook#29]
I set up synching with a test Slack channel, and I want to move it to a different channel. How can I do that? On the website, I see "Questions in this team are synced to your Slack channel," but I don't see a way to unsync and resync.

<img width="755" alt="image" src="https://github.com/user-attachments/assets/ab4afbfb-388d-4cf4-83db-1eb115e1911f">

Would removing the app from Slack and re-adding it work?

**Comment by adam-binks** [comment]
Thanks for pointing this out @patbl - in c6200b3b340047d8dc022b1511ba2cd84297afeb I've added a button to cancel syncing.

<img width="533" alt="image" src="https://github.com/user-attachments/assets/5a95490d-9da0-4771-9957-e745db68a0ee">

You can click this and then set up syncing to your new channel.
