### ISSUE TITLE
Duplicate forecasts entered when using "enter" button

### ISSUE THREAD

**Issue by Stvad** [Sage-Future/fatebook#66]
For me a very natural flow to update the prediction/add a forecast is to:
- Click into the percentage box
- edit number 
- press "enter" to submit

But that results in 2 identical forecasts being generated:
![image](https://github.com/user-attachments/assets/fcbe6a11-d7fc-457c-8fb0-ea6b30526387)

It seems like maybe a new forecast is submitted both on "enter" and on "blur"?

**Comment by jonnyspicer** [comment]
Thanks for reporting this - are you using Firefox? If so, I was able to reproduce it there (but couldn't on Chrome, so would be interested to know if that's the browser you're using). 

I'll take a look at this now and let you know when I've pushed a fix.

**Comment by jonnyspicer** [comment]
I've just deployed a fix, as far as I can tell it's now working as expected in both FireFox and Chromium browsers - feel free to re-open this issue if you're still running into it.

**Comment by Stvad** [comment]
I'm using Firefox, yes and things seem to be working well now, thank you!
