### ISSUE TITLE
Default keyboard shortcut on firefox extension on Mac does not work in google docs 

### ISSUE THREAD

**Issue by JasonGross** [Sage-Future/fatebook#68]
Control+Shift+F is captured by google docs and does not pop up a prediction

**Comment by jonnyspicer** [comment]
I've pushed a new version of the FF extension that changes the default keyboard shortcut on Firefox to `cmd+option+Q` or `ctrl+alt+Q` dependent on OS (with the idea being that the "Q" is for "Question"). I couldn't find any obvious binding collisions with it, feel free to re-open if you do experience any further trouble though.
