### ISSUE TITLE
Scroll on Collaborators tab on mobile breakpoint doesn't work

### ISSUE THREAD

**Issue by SamMakesThings** [Sage-Future/fatebook#78]
Title says it. On mobile sizes specifically, scroll doesn't work when the Collaborators tab is selected. Replicated this on my iPhone 16 Pro, plus on Chrome's mobile device screen size in devtools. (drag to scroll)

Briefly tried to track it down without success - it's not an immediately obvious overflow property issue, size issue, etc.

<img width="391" alt="image" src="https://github.com/user-attachments/assets/7c880b9e-811b-4cde-8733-1bda083dbb8a">

**Comment by Stvad** [comment]
This also happens for me on Android (Chrome)

**Comment by SamMakesThings** [comment]
Beautiful, thank you!
